### ISSUE TITLE
!cbb help doesn't work when bot is added to server; bot is offline

### ISSUE THREAD

**Issue by cobbie** [seanpfeifer/coffeebeanbot#3]
Hi! I tried adding CBB to my server, but it seems like it isn't working as of the moment?

Steps to replicate:
1. Add [CBB](https://discord.com/oauth2/authorize?client_id=347286461252370432&scope=bot) to a server
2. `!cbb help` once it's added to the server

**Comment by seanpfeifer** [comment]
Hello!

Please check your server to see if this is working for you now.

As part of restarting the bot, I've added a [Docker image here](https://github.com/seanpfeifer/coffeebeanbot/packages/316694) and [instructions on how to run this image locally here](https://github.com/seanpfeifer/coffeebeanbot/blob/main/README.md#running-using-docker).  This should make the bot easier to self-host. 😃

**Comment by cobbie** [comment]
Thanks, it works fine now! Big fan of Overwatch btw, haha.
